In [1]:
import pandas as pd

In [2]:
# input 데이터 가져옴
prs = []

with open("input.txt", "r") as f:
    while True:
        line = f.readline()
        if not line: 
            break
        prs.append(line.strip())

In [3]:
prs_split = []
for i in prs:
    prs_split.append(i.split(' '))

In [4]:
# 데이터가 적절한 입력 포맷(N(페이지 개수),M(할당 page frame 개수),W(widow size),K(page reference string 길이))으로 들어오지 않았을 때 예외 처리
if len(prs_split[0]) < 4:
    print('please write in proper form')

In [5]:
# 데이터를 가시적으로 보기 좋게 만들어줌
variable_name = ['process page 갯수', '할당 page frame 갯수', 'window size', 'page reference string 길이']

prs_complete = []
prs_complete.append({})
prs_complete.append([])

k=0
for i in prs_split[0]:
    prs_complete[0][variable_name[k]] = int(i)
    k += 1

for i in prs_split[1]:
    prs_complete[1].append(int(i))

In [6]:
prs_complete

[{'process page 갯수': 6,
  '할당 page frame 갯수': 3,
  'window size': 3,
  'page reference string 길이': 15},
 [0, 1, 2, 3, 2, 3, 4, 5, 4, 1, 3, 4, 3, 4, 5]]

In [7]:
page_reference_string = prs_complete[1]
page_frame_size = prs_complete[0]['할당 page frame 갯수']
window_size = prs_complete[0]['window size']

In [8]:
# page reference string 길이와 실제 page reference string 의 길이가 일치하지 않았을 경우의 예외 처리
if prs_complete[0]['page reference string 길이'] != len(page_reference_string):
    print('page reference string 길이를 제대로 적어주세요.')

In [9]:
# window size 가 page frame size 보다 클 떄의 예외 처리
if window_size > page_frame_size:
    print('window size 는 pag frame size 보다 작아야 합니다.')

In [10]:
# FIFO 기법
from FIFO import FIFO

fifo = FIFO(page_reference_string,page_frame_size,window_size)
result_fifo = fifo.show()

In [11]:
df_fifo = pd.DataFrame()

time_list_fifo = [i+1 for i in range(len(page_reference_string))]

df_fifo['time'] = time_list_fifo
df_fifo['page reference string'] = page_reference_string
df_fifo['memory state'] = result_fifo[0]
df_fifo['page fault'] = result_fifo[1]

In [12]:
print('page fault 횟수: {sum}'.format(sum=sum(result_fifo[1])))
df_fifo

page fault 횟수: 10

    time  page reference string memory state  page fault
0      1                      0          [0]           1
1      2                      1       [0, 1]           1
2      3                      2    [0, 1, 2]           1
3      4                      3    [1, 2, 3]           1
4      5                      2    [1, 2, 3]           0
5      6                      3    [1, 2, 3]           0
6      7                      4    [2, 3, 4]           1
7      8                      5    [3, 4, 5]           1
8      9                      4    [3, 4, 5]           0
9     10                      1    [4, 5, 1]           1
10    11                      3    [5, 1, 3]           1
11    12                      4    [1, 3, 4]           1
12    13                      3    [1, 3, 4]           0
13    14                      4    [1, 3, 4]           0
14    15                      5    [3, 4, 5]           1

In [13]:
#Working Set 기법
from WS import WS

ws = WS(page_reference_string,page_frame_size,window_size)
result_ws = ws.show()

In [14]:
df_ws = pd.DataFrame()

time_list_ws = [i+1 for i in range(len(page_reference_string)-window_size+1)]
df_ws['time'] = time_list_ws
df_ws['page reference string'] = page_reference_string[2:]
df_ws['memory state'] = result_ws[0]
df_ws['page fault'] = result_ws[1]

In [15]:
print('page fault 횟수: {sum}'.format(sum=sum(result_ws[1])))
df_ws

page fault 횟수: 7

    time  page reference string memory state  page fault
0      1                      2    [0, 1, 2]           1
1      2                      3    [1, 2, 3]           1
2      3                      2    [2, 3, 2]           0
3      4                      3    [3, 2, 3]           0
4      5                      4    [2, 3, 4]           1
5      6                      5    [3, 4, 5]           1
6      7                      4    [4, 5, 4]           0
7      8                      1    [5, 4, 1]           1
8      9                      3    [4, 1, 3]           1
9     10                      4    [1, 3, 4]           0
10    11                      3    [3, 4, 3]           0
11    12                      4    [4, 3, 4]           0
12    13                      5    [3, 4, 5]           1